### PR TITLE
Improve kernel color lookup code

### PR DESCRIPTION
**Pull request by pembem22**
Hello, this PR optimizes kernel color lookup code and improves rendering speed. I've added `ccl_static_constant` to the LUT tables like in other files and removed unnecessary loops and functions.

Render speed comparison:
master | Before | After
--- | --- | ---
render_master | render_before | render_after

### CODE REVIEW

**Comment by Smilebags** [comment]
🤯 Firstly, a massive thank you for spending some time to make this improvement and submit a PR.

It's amazing what knowing how to write in a language can improve performance like this. I'm glad it was as easy as this to set up 'proper' constants, I just couldn't figure it out in the time I spent looking into it.

Thanks again, I'll merge it right now. On a side note, I don't recognise your name, are you following the development thread on Devtalk?

**Comment by pembem22** [comment]
Thanks! Yes, I've been following Devtalk thread for some time, but I'm not registered there. I think the main problem was [this](https://github.com/Smilebags/blender/blob/7edd553a7141e7a75ec2fd07e3647678c2ce7993/intern/cycles/kernel/kernel_color.h#L558) `while` which did a lot of unnecessary looping. Also, I've been experimenting recently with adding spectral data support to nodes and will submit a PR later.

**Comment by Smilebags** [comment]
I'm really excited to see what you find, feel free to push a branch and have a WIP PR open here, keen to discuss where possible, I have a lot to learn.

All of this code is very first-pass, as soon as it compiles and behaves correctly it was good enough for now, I really appreciate you going over it and tidying things up. I wasn't aware of the 'unlikely' compiler hint, so that's one thing I've learnt.

Is there any name or tag you would like me to call you by in the devtalk thread?

**Comment by pembem22** [comment]
https://devtalk.blender.org/u/pembem22

**Pull request merged**
